### ISSUE TITLE
Installation failed for Raspberry Pi 4

### ISSUE THREAD

**Issue by bitvijays** [danielparks/puppet-golang#2]
Hello @danielparks Hope you are doing well. Thank you for creating puppet-golang. Much appreciated.

Currently, in `init.pp`, you have defined installation for x64, x86 and Darwin. However, when someone wants to install golang on raspberry pi with ARM architecture. It would install the amd64 version as default setup. Here's the code for your reference.

```
  String[1]        $arch          = $facts['os']['hardware'] ? {
    undef    => 'amd64', # Darwin doesn't have os.hardware.
    'x86_64' => 'amd64',
    'i686'   => '386',
    default  => $facts['os']['hardware'],
  },
```

Could you please add

```
    'aarch64'=> 'armv6l',
``` 
for Raspberry Pi 4. I would also check for previous raspberry Pi v2 and v3 and come back to you.

**Comment by danielparks** [comment]
Thanks for the report!

Could you give me the output of `facter os` on your Pi? The exact contents of the `os` fact depend somewhat on the OS installed as well. Depending on the output I might switch to `$facts['os']['architecture']`.

**Comment by bitvijays** [comment]
@danielparks Here's the output for Raspberry Pi 4

```
os => {
  architecture => "aarch64",
  distro => {
    codename => "eoan",
    description => "Ubuntu 19.10",
    id => "Ubuntu",
    release => {
      full => "19.10",
      major => "19.10"
    }
  },
  family => "Debian",
  hardware => "aarch64",
  name => "Ubuntu",
  release => {
    full => "19.10",
    major => "19.10"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by danielparks** [comment]
Ok, give version 1.0.2 a try and let me know if it works.

**Comment by bitvijays** [comment]
@danielparks Thank you for fixing this for Raspberry Pi 4. Here's the output for Raspberry Pi 2B and 3B. It would need to add one more line for architecture `armv7l`.
```
os => {
  architecture => "armv7l",
  distro => {
    codename => "bionic",
    description => "Ubuntu 18.04.3 LTS",
    id => "Ubuntu",
    release => {
      full => "18.04",
      major => "18.04"
    }
  },
  family => "Debian",
  hardware => "armv7l",
  name => "Ubuntu",
  release => {
    full => "18.04",
    major => "18.04"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by danielparks** [comment]
Hm… backing up a step, are you sure that “armv6l” is the correct architecture for the 4? If I understand correctly, that’s a 32 bit architecture and the Raspberry PI 4 is actually a 64 bit ARMv8. I imagine it’s backward compatible, but I’m pretty sure the correct binary is the “arm64” one.

Could you try the following on your Raspberry PI 4?

```puppet
class { 'golang':
  'arch' => 'arm64',
}
```

I’ll prep a PR for the older Pis. Thanks again!

**Comment by bitvijays** [comment]
My apologies, armv7l is for Raspberry 2 and 3. The output above was from Raspberry Pi 2/3.

**Comment by danielparks** [comment]
Ok, should be working for all of them now. :)

**Comment by bitvijays** [comment]
Thanks @danielparks your quick response is really appreciated.

**Comment by danielparks** [comment]
No problem! Glad it’s useful.
